### ISSUE TITLE
Идея, настройки умного дома, IoT

### ISSUE THREAD

**Issue by skar404** [aveic/vax#1]
Хотел предложить идею, возможность управлять и настраивать умный дом (умный дом можно заменить различными несвязными датчиками). 

В чем мысль, возможность комбинировать различные датчики, допустим датчик температуры и управления батареями или кондиционером с помощью вашего интереса, реализация некого API для IoT устройств.

И вопрос, проект будет двигаться в данном направлении?

> В принципе можно думать более глобально, в плоть до управления микро сервисами и хождениям трафика между серверами допустим

**Comment by evazamtz** [comment]
> И вопрос, проект будет двигаться в данном направлении?

Сам проект никак не привязан к исполняющей стороне. Он просто позволяет в браузере строить графы поверх придуманной вами грамматики. Интерпретация графа (или дерева) всегда будет оставаться за вами.

> В чем мысль, возможность комбинировать различные датчики, допустим датчик температуры и управления батареями или кондиционером с помощью вашего интереса, реализация некого API для IoT устройств.

Да можно с лёгкостью придумать для этого удобные элементы и описать их в грамматике. Могу помощь вам составить такую грамматику.

**Comment by VladimirSFilippov** [comment]
> Хотел предложить идею, возможность управлять и настраивать умный дом (умный дом можно заменить различными несвязными датчиками).

Для этого же можно использовать Node-RED. Но если у вас есть желание - готов помочь в разработке.
