### ISSUE TITLE
Correct format of function?

### ISSUE THREAD

**Issue by j2l** [aveic/vax#4]
Here's my [A,B] function, is that correct?
![image](https://user-images.githubusercontent.com/65325/34492016-16e271f8-efe6-11e7-82ea-e29f3ff3188f.png)

**Comment by evazamtz** [comment]
Yes it is, but it won't work, since both _Input_ nodes have the same value of attribute "_Name_" (I). Change them to "I1" and "I2" for example. And I know it's not obvious, but u have to compile user functions by pressing _Ctrl+E_ in order for them to be stored.

**Comment by j2l** [comment]
It makes sense. Thank you!
